name: ParaBank API Tests CI

on: [push]

jobs:
  newman_api_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run "ParaBank API Tests.postman_collection.json" -e "Parabank.postman_environment.json"
